apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-demo
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rabbitmq-pvc.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml
  - orders-api-deployment.yaml
  - orders-api-service.yaml
  - shipping-api-deployment.yaml
  - shipping-api-service.yaml
  - ingress.yaml
