apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-demo-secret
type: Opaque
stringData:
  RabbitMq__UserName: demo
  RabbitMq__Password: demo-password
  RABBITMQ_DEFAULT_USER: demo
  RABBITMQ_DEFAULT_PASS: demo-password
