apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: rabbitmq-demo/orders-api
    newName: rabbitmq-demo/orders-api
    newTag: dev
  - name: rabbitmq-demo/shipping-api
    newName: rabbitmq-demo/shipping-api
    newTag: dev
